[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_program = "GSAh2GuhF6niNFhwV4Yd2Kbd18m3N7a6ysaseCrQiKy7"

[registry]
url = "https://api.apr.dev"

[programs.mainnet]
onchain_program = "GSAh2GuhF6niNFhwV4Yd2Kbd18m3N7a6ysaseCrQiKy7"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
