[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_program = "6etp2LgigJcYA9GqHecM7BtD1WJDzcdptQfi3tEntHrh"

[registry]
url = "https://api.apr.dev"

[programs.mainnet]
onchain_program = "6etp2LgigJcYA9GqHecM7BtD1WJDzcdptQfi3tEntHrh"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
